version: "3.4"

services:
  fluentd:
    build: ./fluentd-image
    image : fluentd-estest:latest
    ports:
      - "24224:24224"
    volumes:
      - ./configs/fluent.conf:/fluentd/etc/fluent.conf
    environment:
      - LOCALHOST=${LOCALHOST}
      - ELASTICSEARCH_HOST=${LOCALHOST}
      - ELASTICSEARCH_PORT=9200
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=${ES_JAVA_OPTS:--Xms1g -Xmx1g}
      - discovery.type=single-node
      - xpack.monitoring.collection.enabled=true
    # volumes:
    #   - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image : docker.elastic.co/kibana/kibana:7.3.0
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://${LOCALHOST}:9200

